// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjdslybdljdkacwxbmdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZHNseWJkbGpka2Fjd3hibWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTUzNDAsImV4cCI6MjA3MDA5MTM0MH0.D2-LCXJFt1ptGRu8NQzyi1k35CawtsL0rHdwzT0D2EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});